name: Push Replicate Model
on:
  push:
    branches:
      - main

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Setup Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}
          install-cuda: false

      - name: Push to Replicate
        run: cog push r8.im/${{ vars.REPLICATE_MODEL }}
